/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "reserve_constants.h"



const reserveConstants g_reserve_constants;

reserveConstants::reserveConstants() {
}



