/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef reserve_CONSTANTS_H
#define reserve_CONSTANTS_H

#include "reserve_types.h"



class reserveConstants {
 public:
  reserveConstants();

};

extern const reserveConstants g_reserve_constants;



#endif
